### PR TITLE
Clean up for druntime 2.071

### PR DESCRIPTION
**Pull request by Calrama**
Remove everything that is shipped with druntime 2.071.
Sadly, there still seem to be some things (like `SO_REUSEPORT`) to be missing (meaning this module is not yet obsolete).

### CODE REVIEW

**Comment by wilzbach** [comment]
Wow removing 1.1K lines. That's a great cleanup! 
But doesn't this mean you temporarily loose ldc stable support? Afaict the latest ldc version ships with 2.071, but it's still in beta.

**Comment by etcimon** [comment]
For backwards compatibility it would probably require a `__VERSION__ >= 2071` at first, I use 2.070 myself still because my production-level project isn't ready for 2.071 yet due to some regressions in win64 that I haven't addressed yet

**Comment by etcimon** [comment]
It's possible that this would work with 2.070, I'd have to check

**Comment by Calrama** [comment]
`$ dub test --compiler=ldc2` runs fine for me, though I believe they may have been added earlier. I'll have a look.

**Comment by etcimon** [comment]
Oh I completely forgot that the unit tests covered all the way down to 2.068. OK Thanks for this!

**Pull request merged**
