### PR TITLE
Cleanup and fix for epoll_event alignment on non-X86

### PR DESCRIPTION
**Pull request by Calrama**
As documented [here](https://github.com/dlang/druntime/commit/c94547af8d55e1490b51aac358171b761da6a657), epoll_event is only packed on
X86 (and X86_64), so backport that fix. Also, remove everything that can
be imported from druntime.

### CODE REVIEW

**Comment by Calrama** [comment]
Hm, I don't know why the check fails for dmd 2.069, since the module is [clearly present](https://github.com/dlang/druntime/tree/v2.069.0/src/core/sys/linux/timerfd.d) in druntime 2.069.0.

**Comment by etcimon** [comment]
Thanks!

**Comment by etcimon** [comment]
It's not copied into the includes folder up until 2.070.0: https://github.com/dlang/druntime/blob/v2.069.2/mak/COPY

**Comment by etcimon** [comment]
I wonder if everything is nothrow enough to clean up all the useless try/catch blocks =)

**Pull request merged**
