### PR TITLE
Fix long->time_t conversion error on 32-bit.

### PR DESCRIPTION
**Pull request by s-ludwig**
Just typed this in the GitHub editor, let's see if it compiles ;)

### CODE REVIEW

**Comment by etcimon** [comment]
Never tried the send timeout yet either :p

**Comment by etcimon** [comment]
Out of context but in vibe the 0 seconds timeout and timer has undefined behavior e.g. WaitForData or keepalive Should it trigger immediately or never

**Comment by s-ludwig** [comment]
My plan was to change all places to mean immediate for `0` and infinite for `Duration.max`. I'm not sure though if everything is consistent, yet.

**Comment by etcimon** [comment]
Ok I have my defaults to 0 for infinite but recently discovered that setTimer used it as immediate. That was a source of bugs requiring yieldAndResume to handle its own task. Anyways, I think ill switch the behavior to what you say in the botan stream because its inconsistent right now

**Comment by etcimon** [comment]
Quite a few places needed the correction: https://github.com/etcimon/vibe.d/commit/9eb87c2a24ac094e7bab2ed21c768a05f0768398

I'll prepare a pull request soon enough.

Btw, I came across a bug with vibe.data.serialization. It has to do with running toISOExtString() on a SysTime.init, it's going to segfault on a null timezone in adjTime, not sure if std.datetime is to blame on that..

**Pull request merged**
